services:
  - type: web
    name: wandertribe
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyD4DBv28VDq3Y8BjUnDLE6jhS1WVC2zXzw
      - key: GROQ_API_KEY
        value: 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
