services:
  - type: web
    name: wandertribe-api
    runtime: docker
    dockerfilePath: ./Travel/Dockerfile
    dockerContext: ./Travel
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
