import { useState } from 'react';
import { chatApi } from '../api';
import ReactMarkdown from 'react-markdown';

export default function Itinerary({ tripId }) {
  const [itinerary, setItinerary] = useState('');
  const [seasonInfo, setSeasonInfo] = useState('');
  const [loading, setLoading] = useState(false);

  const generateItinerary = async () => {
    setLoading(true);
    try {
      const { data } = await chatApi.curate(tripId);
      setItinerary(data.itinerary);
    } catch (err) {
      setItinerary('Failed to generate itinerary. Please try again.');
    }
    setLoading(false);
  };

  const getSeasonInfo = async () => {
    setLoading(true);
    try {
      const { data } = await chatApi.getSeason(tripId);
      setSeasonInfo(data.recommendation);
    } catch (err) {
      setSeasonInfo('Failed to get season info.');
    }
    setLoading(false);
  };

  const downloadPDF = () => {
    const content = itinerary || seasonInfo;
    if (!content) return;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>WanderTribe - Trip Itinerary</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            line-height: 1.7; color: #1a1a2e; padding: 40px;
            max-width: 800px; margin: 0 auto;
          }
          .header {
            text-align: center; margin-bottom: 30px; padding-bottom: 20px;
            border-bottom: 3px solid #10b981;
          }
          .header h1 { color: #10b981; font-size: 28px; margin-bottom: 5px; }
          .header p { color: #666; font-size: 14px; }
          h1, h2, h3 { color: #1a1a2e; margin: 20px 0 10px; }
          h2 { color: #10b981; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
          h3 { color: #059669; }
          ul, ol { margin-left: 20px; margin-bottom: 10px; }
          li { margin-bottom: 5px; }
          strong { color: #10b981; }
          p { margin-bottom: 10px; }
          .footer {
            margin-top: 40px; padding-top: 15px; border-top: 2px solid #10b981;
            text-align: center; color: #999; font-size: 12px;
          }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>WanderTribe</h1>
          <p>AI-Curated Travel Itinerary • Generated ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
        </div>
        <div id="content"></div>
        <div class="footer">
          <p>Generated by WanderTribe AI • wandertribe.app</p>
          <p>Prices are estimates and may vary by season. Always confirm before booking.</p>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"><\/script>
        <script>
          document.getElementById('content').innerHTML = marked.parse(${JSON.stringify(content)});
          setTimeout(() => window.print(), 500);
        <\/script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="p-4 sm:p-6">
      <div className="flex flex-wrap gap-3 mb-8">
        <button onClick={generateItinerary} disabled={loading}
          className="px-5 sm:px-6 py-3 bg-emerald-500 hover:bg-emerald-400 disabled:opacity-50 rounded-xl font-medium transition-all hover:scale-105 flex items-center gap-2 text-sm sm:text-base">
          {loading ? '⏳ Generating...' : '🤖 Generate AI Itinerary'}
        </button>
        <button onClick={getSeasonInfo} disabled={loading}
          className="px-5 sm:px-6 py-3 bg-cyan-500 hover:bg-cyan-400 disabled:opacity-50 rounded-xl font-medium transition-all hover:scale-105 flex items-center gap-2 text-sm sm:text-base">
          {loading ? '⏳ Loading...' : '📅 Best Season Guide'}
        </button>
        {(itinerary || seasonInfo) && (
          <button onClick={downloadPDF}
            className="px-5 sm:px-6 py-3 bg-violet-500 hover:bg-violet-400 rounded-xl font-medium transition-all hover:scale-105 flex items-center gap-2 text-sm sm:text-base">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
            Download PDF
          </button>
        )}
      </div>

      {!itinerary && !seasonInfo && (
        <div className="text-center py-16 text-white/30">
          <span className="text-6xl block mb-4">🗓️</span>
          <p className="text-2xl mb-2">No itinerary yet</p>
          <p className="max-w-md mx-auto text-base">Click "Generate AI Itinerary" to create a personalized day-by-day plan based on your group's ideas, budget, and travel style.</p>
          <p className="mt-4 text-sm text-white/20">You can download the itinerary as a PDF once generated.</p>
        </div>
      )}

      {itinerary && (
        <div className="bg-white/5 border border-white/10 rounded-2xl p-5 sm:p-8 mb-6">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-xl sm:text-2xl font-bold flex items-center gap-2">
              <span>🗺️</span> Your AI-Curated Itinerary
            </h3>
          </div>
          <div className="prose prose-invert prose-sm sm:prose-lg max-w-none">
            <ReactMarkdown>{itinerary}</ReactMarkdown>
          </div>
        </div>
      )}

      {seasonInfo && (
        <div className="bg-white/5 border border-cyan-500/20 rounded-2xl p-5 sm:p-8">
          <h3 className="text-xl sm:text-2xl font-bold mb-6 flex items-center gap-2">
            <span>📅</span> Season Guide
          </h3>
          <div className="prose prose-invert prose-sm sm:prose-lg max-w-none">
            <ReactMarkdown>{seasonInfo}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  );
}
